### PR TITLE
Migrating sts

### PR DESCRIPTION
**Pull request by s-zanella**

### CODE REVIEW

**Comment by msprotz** [comment]
If the build succeeded, let's merge?

Congrats on a hard piece of work!

**Comment by s-zanella** [comment]
Yes, please. 
I can't merge. VSTS notifications aren't working.

**Comment by msprotz** [comment]
I'm happy to make you admin. @darrenge can you investigate why we have two VSTS integrations while only one reports success? Thanks!

**Comment by darrenge** [comment]
I don't know what is going on with VSTS integration not reporting. miTLS triggers are the same as FStar triggers. It works most of the time but there is a history of hiccups here and there.

**Pull request merged**
