### PR TITLE
Add FFI wrappers to support curl

### PR DESCRIPTION
**Pull request by BarryBo**
Add C-callable wrappers to miTLS, callable from curl or other TLS
clients and servers.  This generates a libmitls.dll that contains miTLS and C-callable entrypoints.

At this point, it works well enough to negotiate TLS 1.2 to web page URLs on google.com and fetch their contents.

**Future work**
- TLS 1.3 support
- remove the IO.print_string calls from the miTLS "expected" codepaths (possibly by wrapping them, so they are available, but don't print in the retail build).  They currently interfere with using curl to download web pages, as it dumps the downloaded content to stdout.
- reduce fragility of the "state" object on the C side by removing the need to make the caller's storage a GC root.  The next version will store a C heap pointer in the caller's buffer, and make the C heap allocation a GC root.  The extra level of indirection adds safety at minimal size/speed overhead.
- sync my branch forward to the main branch... my branch is 3 weeks stale
- improve performance via caller-allocated buffers instead of the FFI layer using malloc() to allocate new packet buffers.

**To review**, I recommend the following order:
1. Start with mitlsffi.h - that defines the C-callable interface into miTLS.  
2. Then head to FFI.ml to see the FStar side of that interface.  
3.  ffi.c contains the glue code between the two worlds, using the OCaml FFI to allocate memory, call functions, etc.
4.  TestClient13.fst has expanded considerably - it implements the miTLS side of TLS.  The new code is almost all cloned code from TestClient and TestClient13, wrapped in glue code to marshal and unmarshal state.

**Questions for the team**
1. Should I refactor the ffi code out of TestClient13.fst into a separate ffi.fst file?  
2. Is there a better way to capture and replay state than the many "ffiState*" structs I created?  The process of creating them was tedious and error-prone, especially deducing the types of each field.

### CODE REVIEW

**Comment by s-zanella** [comment]
That's impressive work!

_1. Should I refactor the ffi code out of TestClient13.fst into a separate ffi.fst file?_
I think you should. The code for the test client itself is still calling directly into KeySchedule and Handshake. Perhaps we could update it to use just ffi.fst, or write a separate test client using ffi.fst.

**One question**: Why do you need mitlsffi.h to expose internals of the TLS handshake? That isn't necessary to implement the cURL virtual TLS interface (https://github.com/curl/curl/blob/master/lib/vtls/vtls.h). Is it because the top-level miTLS API is not yet finished? 
I would expect a higher-level interface, in terms of {connect,accept,recv,write,...} rather than functions like handle_server_key_exchange. 

You may want to have a look at how the Mirage developers implemented C bindings for nqsb-tls. They used their Ctypes library: https://github.com/mirleft/libnqsb-tls/blob/master/lib/bindings.ml

**Comment by nikswamy** [comment]
@ad-l @protz @s-zanella: I think you guys understand this aspect the best. Can you review and merge Barry's request.

**Comment by BarryBo** [comment]
☺

I opted to expose the TLS handshake internals in order to separate the TLS code from the socket transport underneath it.  Three reasons:


1.       The current miTLS FFI does not need knowledge of socket identifiers/handles or how to send and receive socket data.  To me, that feels like a better choice, especially for Windows with its exotica of I/O completion ports and overlapped I/O.  Even Unix-style sockets require OS-specific code to deal with nonblocking sockets, like those that curl opens.  The FFI C-side code would need an autoconf script to help deal with the variability, adding dev work whenever miTLS is built for a different target OS or hosted in a different app.  I looked at the other SSL libraries that curl supports, and they all have to carry their own platform-specific socket code… that doesn’t feel like the right abstraction.


2.       Also, currently in miTLS, the TLS handshake isn’t encapsulated anywhere other than the TestClient apps – code that appears external to miTLS itself.


3.       I couldn’t figure out a good way to pass C function pointers into OCaml, for socket callbacks.  If we had that mechanism, we could encapsulate the TLS handshake entirely in miTLS without losing the separation from sockets.  I think I can approximate that using OCaml-to-C function calls to helper C functions linked into the libmitls.dll, and have those fixed functions make the indirect function call.  One extra hop for much reduction in code complexity.

I’m completely flexible on this topic.  Now that I have mastered the FFI and curl, it’s straightforward to refactor code as needed.
Barry

**Comment by sishtiaq** [comment]
I think Ctypes would let you do your #3, pass C function pointers into OCaml. Something to add to Future Work, maybe?

**Comment by BarryBo** [comment]
Agreed - I’m working on pulling a function pointer through right now.

I’m going to try bringing TLS 1.3 through FFI using that technique, so we can compare with the TLS 1.2 component-wise style.

Barry

**Comment by BarryBo** [comment]
I'm closing this pull request and about to create a new one that addresses the issues noted here.

**Pull request closed without merging**
